### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by MarieJoigneau** [AgrocampusDS/visualisation-mariealexfrancoise#1]
Bonjour madame,

Ci-joint les packages que nous utilisons. Je pense que vous les avez tous cependant.

Bien à vous,
Marie

library(ggplot2)
library(tidyverse)
library(ggsci)
library(leaflet)
library(plotly)
library(egg)
library(ggpubr)
library(patchwork)
library(viridis)
library(scales)

**Comment by MarieEtienne** [comment]
Done
